### ISSUE TITLE
Cluster Level OCI Authentication Provider(aka Multitenancy support)

### ISSUE THREAD

**Issue by shyamradhakrishnan** [oracle/cluster-api-provider-oci#203] opened 2023-01-17 04:44 UTC
**What would you like to be added**:
Users should be able to specify different user principals per cluster.

**Why is this needed**:
In some large organisations, a single management cluster may be shared across multiple smaller teams and even tenancies. Hence each team may like to use its own user credentials for the workload cluster they create.

**Comment by joekr** [comment] 2023-01-17 16:47
Is this a duplicate of https://github.com/oracle/cluster-api-provider-oci/issues/180 ?

**Comment by shyamradhakrishnan** [comment] 2023-01-18 04:15
Slightly different from 180, that is a bug because instance principal does not support multi tenancy support right now, this ons is supporting multitenancy using userprincipal.

**Comment by shyamradhakrishnan** [comment] 2023-02-08 09:19
Fixed via attached PR

**Closed** 2023-02-08 09:19 UTC
Labels: enhancement
